[mypy]
ignore_missing_imports = True
no_implicit_optional = False
disable_error_code = var-annotated, assignment, arg-type, union-attr, attr-defined, index, operator, return-value, call-overload, misc, override, call-arg
